window.MARKET_DATA = {
  "meta": {
    "snapshotAt": "2026-09-17T16:49:53+09:00",
    "sourceFile": "아쎄르_수정.xlsx",
    "comparisonBasis": "정확한 MTM·용량이 일치하는 개별 상품 페이지의 공개 판매가와 배송비 기준",
    "exclusions": "개인화 쿠폰, 카드사별 혜택, 적립금, 로그인 전용 와우 최대혜택은 기본 비교가에서 제외",
    "monitoring": {
      "enabled": true,
      "quickWatch": "매일 08:00 KST",
      "fullResearch": "기본+정밀 동시 실행",
      "dashboardSync": "GitHub Pages 자동 반영",
      "lastAttemptAt": "2026-09-17T16:49:53+09:00",
      "lastAttemptStatus": "success",
      "lastAttemptText": "Acer 일반 Chrome 조사 · 현재가 확인 10/10",
      "collectionRoute": "Windows PC · 일반 Chrome 확장프로그램",
      "competitionLastAttemptAt": "2026-09-17T16:49:53+09:00"
    },
    "brand": "Acer"
  },
  "products": [
    {
      "storage": "1TB",
      "display": "Nitro V 16",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1558000,
          "instantDiscount": 0,
          "couponDiscount": 227800,
          "cardDiscount": 0,
          "finalPrice": 1330200,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "A",
          "confidenceText": "정확 Item ID의 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9573633117?itemId=28575928128&vendorItemId=95520178041",
          "cardEvidenceSource": "dom-snapshot",
          "availabilityCheckedAt": "2026-09-17 16:49",
          "srp": 1558000,
          "observedListPrice": 1558000,
          "preCardPrice": 1330200,
          "priceBasisType": "crossed-out",
          "cardBenefitStatus": "none",
          "cardRate": null,
          "cardMaxDiscount": null,
          "cardProviders": [],
          "cardBenefitText": "",
          "checkoutDiscountStatus": "captured",
          "checkoutDiscountReason": "total-matched-one-or-more-labels-omitted",
          "wowInstantDiscount": 80000,
          "wowCouponDiscount": 147800,
          "checkoutDiscountCheckedAt": "2026-09-17T07:39:59.155Z",
          "alertEligible": true,
          "priceCheckedAt": "2026-09-17 16:49",
          "checkoutCouponDiscount": 0
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "판매중",
          "displayPrice": 1664910,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1664910,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 1664920,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1664920,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "롯데ON",
          "status": "판매중",
          "displayPrice": 1670380,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1670380,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "판매중",
          "displayPrice": 1670380,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1670380,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 1878000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1878000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "슈프림컴",
          "status": "판매중",
          "displayPrice": 1880000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1880000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "피씨블랙",
          "status": "판매중",
          "displayPrice": 1648000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1648000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 1665610,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-17 08:02",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=ANV16-I31-514Z"
        }
      ],
      "mtm": "ANV16-I31-514Z",
      "productId": "9573633117",
      "itemId": "28575928128",
      "vendorItemId": "95520178041",
      "category": "Notebook",
      "srp": 1558000
    },
    {
      "storage": "512GB",
      "display": "Aspire Go 14",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1429000,
          "instantDiscount": 0,
          "couponDiscount": 170000,
          "cardDiscount": 0,
          "finalPrice": 1259000,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "A",
          "confidenceText": "정확 Item ID의 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9681715061?itemId=28951318769&vendorItemId=95881909514",
          "cardEvidenceSource": null,
          "availabilityCheckedAt": "2026-09-17 16:49",
          "srp": 1429000,
          "observedListPrice": 1429000,
          "preCardPrice": 1259000,
          "priceBasisType": "crossed-out",
          "cardBenefitStatus": "none",
          "cardRate": null,
          "cardMaxDiscount": null,
          "cardProviders": [],
          "cardBenefitText": "",
          "checkoutDiscountStatus": "captured",
          "checkoutDiscountReason": "total-matched-one-or-more-labels-omitted",
          "wowInstantDiscount": 50000,
          "wowCouponDiscount": 0,
          "checkoutDiscountCheckedAt": "2026-09-17T07:40:55.673Z",
          "alertEligible": true,
          "priceCheckedAt": "2026-09-17 16:49",
          "checkoutCouponDiscount": 120000
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 1309000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1309000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "판매중",
          "displayPrice": 1429000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1429000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "판매중",
          "displayPrice": 1429000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1429000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 1528080,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1528080,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "슈프림컴",
          "status": "판매중",
          "displayPrice": 1590000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1590000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "롯데ON",
          "status": "판매중",
          "displayPrice": 1766240,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1766240,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "피씨블랙",
          "status": "판매중",
          "displayPrice": 1270000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1270000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 1309000,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-17 08:02",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=AG14-I71M-972S"
        }
      ],
      "mtm": "AG14-I71M-972S",
      "productId": "9681715061",
      "itemId": "28951318769",
      "vendorItemId": "95881909514",
      "category": "Notebook",
      "srp": 1429000
    },
    {
      "storage": "512GB",
      "display": "Aspire Go 14",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1569000,
          "instantDiscount": 0,
          "couponDiscount": 180000,
          "cardDiscount": 0,
          "finalPrice": 1389000,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "A",
          "confidenceText": "정확 Item ID의 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9681715061?itemId=28951318771&vendorItemId=95881909515",
          "cardEvidenceSource": null,
          "availabilityCheckedAt": "2026-09-17 16:49",
          "srp": 1569000,
          "observedListPrice": 1569000,
          "preCardPrice": 1389000,
          "priceBasisType": "crossed-out",
          "cardBenefitStatus": "none",
          "cardRate": null,
          "cardMaxDiscount": null,
          "cardProviders": [],
          "cardBenefitText": "",
          "checkoutDiscountStatus": "captured",
          "checkoutDiscountReason": "total-matched-one-or-more-labels-omitted",
          "wowInstantDiscount": 50000,
          "wowCouponDiscount": 0,
          "checkoutDiscountCheckedAt": "2026-09-17T07:42:01.266Z",
          "alertEligible": true,
          "priceCheckedAt": "2026-09-17 16:49",
          "checkoutCouponDiscount": 130000
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 1439000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1439000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123763381"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "슈프림컴",
          "status": "판매중",
          "displayPrice": 1630000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1630000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123763381"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 1673710,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1673710,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123763381"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "노트캐슬",
          "status": "판매중",
          "displayPrice": 1590000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1590000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123763381"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 1439000,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-17 08:02",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=123763381"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=AG14-I71M-96C5"
        }
      ],
      "mtm": "AG14-I71M-96C5",
      "productId": "9681715061",
      "itemId": "28951318771",
      "vendorItemId": "95881909515",
      "category": "Notebook",
      "srp": 1569000
    },
    {
      "storage": "1TB",
      "display": "Predator Helios Neo 16S",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 4099000,
          "instantDiscount": 996570,
          "couponDiscount": 70000,
          "cardDiscount": 30324,
          "finalPrice": 3002106,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "A",
          "confidenceText": "정확 Item ID의 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9573633117?itemId=26004597899&vendorItemId=92986675922",
          "cardEvidenceSource": "dom-snapshot",
          "availabilityCheckedAt": "2026-09-17 16:49",
          "srp": 4099000,
          "observedListPrice": 3102430,
          "preCardPrice": 3032430,
          "priceBasisType": "crossed-out",
          "cardBenefitStatus": "captured",
          "cardRate": 1,
          "cardMaxDiscount": 31020,
          "cardProviders": [
            "NH농협",
            "신한",
            "BC",
            "하나"
          ],
          "cardBenefitText": "최대 1% 카드 즉시할인 (신한, BC, NH농협, 하나)",
          "checkoutDiscountStatus": "missing",
          "checkoutDiscountReason": "buy-now-button-not-found",
          "wowInstantDiscount": null,
          "wowCouponDiscount": null,
          "checkoutDiscountCheckedAt": "",
          "alertEligible": true,
          "priceCheckedAt": "2026-09-17 16:49",
          "checkoutCouponDiscount": null
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 3675000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 3675000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=93445997"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "(주)두리칸",
          "status": "판매중",
          "displayPrice": 3690000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 3690000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=93445997"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "하이마트",
          "status": "판매중",
          "displayPrice": 3887040,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 3887040,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=93445997"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 3675000,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-17 08:02",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=93445997"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=PHN16S-71-949J"
        }
      ],
      "mtm": "PHN16S-71-949J",
      "productId": "9573633117",
      "itemId": "26004597899",
      "vendorItemId": "92986675922",
      "category": "Notebook",
      "srp": 4099000
    },
    {
      "storage": "512GB",
      "display": "Swift Go 14 AI",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1689000,
          "instantDiscount": 0,
          "couponDiscount": 30000,
          "cardDiscount": 93320,
          "finalPrice": 1565680,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "A",
          "confidenceText": "정확 Item ID의 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9616664363?itemId=28714706385&vendorItemId=95655361667",
          "cardEvidenceSource": null,
          "availabilityCheckedAt": "2026-09-17 16:49",
          "srp": 1689000,
          "observedListPrice": 1689000,
          "preCardPrice": 1659000,
          "priceBasisType": "crossed-out",
          "cardBenefitStatus": "captured",
          "cardRate": 6,
          "cardMaxDiscount": 93320,
          "cardProviders": [
            "NH농협",
            "BC",
            "하나"
          ],
          "cardBenefitText": "최대 6% 카드 즉시할인 (BC, NH농협, 하나)",
          "checkoutDiscountStatus": "captured",
          "checkoutDiscountReason": "total-matched-one-or-more-labels-omitted",
          "wowInstantDiscount": 30000,
          "wowCouponDiscount": 0,
          "checkoutDiscountCheckedAt": "2026-09-17T07:44:12.715Z",
          "alertEligible": true,
          "priceCheckedAt": "2026-09-17 16:49",
          "checkoutCouponDiscount": 0
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 1689000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1689000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "슈프림컴",
          "status": "판매중",
          "displayPrice": 1689000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1689000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "판매중",
          "displayPrice": 1715800,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1715800,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "판매중",
          "displayPrice": 1715800,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1715800,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 1945200,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1945200,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "하이마트",
          "status": "판매중",
          "displayPrice": 1969000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1969000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "롯데ON",
          "status": "판매중",
          "displayPrice": 2541760,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2541760,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "컴투게더",
          "status": "판매중",
          "displayPrice": 1470000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1470000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 1559000,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-17 08:02",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=SFG14-I71-57P5"
        }
      ],
      "mtm": "SFG14-I71-57P5",
      "productId": "9616664363",
      "itemId": "28714706385",
      "vendorItemId": "95655361667",
      "category": "Notebook",
      "srp": 1689000
    },
    {
      "storage": "1TB",
      "display": "Swift Go 14 AI",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1229000,
          "instantDiscount": 0,
          "couponDiscount": 152910,
          "cardDiscount": 0,
          "finalPrice": 1076090,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "A",
          "confidenceText": "정확 Item ID의 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9428079675?itemId=28287192873&vendorItemId=95240133006",
          "cardEvidenceSource": null,
          "availabilityCheckedAt": "2026-09-17 16:49",
          "srp": 1229000,
          "observedListPrice": 1229000,
          "preCardPrice": 1076090,
          "priceBasisType": "crossed-out",
          "cardBenefitStatus": "none",
          "cardRate": null,
          "cardMaxDiscount": null,
          "cardProviders": [],
          "cardBenefitText": "",
          "checkoutDiscountStatus": "captured",
          "checkoutDiscountReason": "total-matched-one-or-more-labels-omitted",
          "wowInstantDiscount": 30000,
          "wowCouponDiscount": 0,
          "checkoutDiscountCheckedAt": "2026-09-17T07:45:18.824Z",
          "alertEligible": true,
          "priceCheckedAt": "2026-09-17 16:49",
          "checkoutCouponDiscount": 122910
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 1358080,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1358080,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "판매중",
          "displayPrice": 1358090,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1358090,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "판매중",
          "displayPrice": 1358090,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1358090,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "롯데ON",
          "status": "판매중",
          "displayPrice": 1359000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1359000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "KTG",
          "status": "판매중",
          "displayPrice": 1368990,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1368990,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 2035000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2035000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "신세계컴",
          "status": "판매중",
          "displayPrice": 1208000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1208000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 1358790,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-17 08:02",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=SFG14-75-508U"
        }
      ],
      "mtm": "SFG14-75-508U",
      "productId": "9428079675",
      "itemId": "28287192873",
      "vendorItemId": "95240133006",
      "category": "Notebook",
      "srp": 1229000
    },
    {
      "storage": "1TB",
      "display": "Swift Go 16 AI · 리퍼비시",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1659000,
          "instantDiscount": null,
          "couponDiscount": 69900,
          "cardDiscount": 0,
          "finalPrice": 2260100,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "A",
          "confidenceText": "정확 Item ID의 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9573633117?itemId=28029585486&vendorItemId=94986693706",
          "cardEvidenceSource": null,
          "availabilityCheckedAt": "2026-09-17 16:49",
          "srp": 1659000,
          "observedListPrice": 2330000,
          "preCardPrice": 2260100,
          "priceBasisType": "crossed-out",
          "cardBenefitStatus": "none",
          "cardRate": null,
          "cardMaxDiscount": null,
          "cardProviders": [],
          "cardBenefitText": "",
          "checkoutDiscountStatus": "missing",
          "checkoutDiscountReason": "buy-now-button-not-found",
          "wowInstantDiscount": null,
          "wowCouponDiscount": null,
          "checkoutDiscountCheckedAt": "",
          "alertEligible": true,
          "priceCheckedAt": "2026-09-17 16:49",
          "checkoutCouponDiscount": null
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 1669030,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1669030,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122702450"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 1808080,
          "condition": "정확한 MTM 상품 페이지가 현재 일시 품절",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-17 08:02",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=122702450"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=SFG16-74-7412"
        }
      ],
      "mtm": "SFG16-74-7412",
      "productId": "9573633117",
      "itemId": "28029585486",
      "vendorItemId": "94986693706",
      "category": "Notebook",
      "srp": 1659000
    },
    {
      "storage": "1TB",
      "display": "Swift Go 16 AI",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1829000,
          "instantDiscount": 0,
          "couponDiscount": 150000,
          "cardDiscount": 16790,
          "finalPrice": 1662210,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "A",
          "confidenceText": "정확 Item ID의 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9483273252?itemId=28237319655&vendorItemId=95190959758",
          "cardEvidenceSource": "dom-snapshot",
          "availabilityCheckedAt": "2026-09-17 16:49",
          "srp": 1829000,
          "observedListPrice": 1829000,
          "preCardPrice": 1679000,
          "priceBasisType": "crossed-out",
          "cardBenefitStatus": "captured",
          "cardRate": 1,
          "cardMaxDiscount": 16790,
          "cardProviders": [
            "NH농협",
            "신한",
            "BC",
            "하나"
          ],
          "cardBenefitText": "최대 1% 카드 즉시할인 (신한, BC, NH농협, 하나)",
          "checkoutDiscountStatus": "captured",
          "checkoutDiscountReason": "total-matched-one-or-more-labels-omitted",
          "wowInstantDiscount": 0,
          "wowCouponDiscount": 0,
          "checkoutDiscountCheckedAt": "2026-09-17T07:47:08.301Z",
          "alertEligible": true,
          "priceCheckedAt": "2026-09-17 16:49",
          "checkoutCouponDiscount": 150000
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "슈프림컴",
          "status": "판매중",
          "displayPrice": 2365000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2365000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "판매중",
          "displayPrice": 2398390,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2398390,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "판매중",
          "displayPrice": 2398390,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2398390,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 2398400,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2398400,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 2399000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2399000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "롯데ON",
          "status": "판매중",
          "displayPrice": 2785560,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2785560,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "피씨블랙",
          "status": "판매중",
          "displayPrice": 2040000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2040000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 2365000,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-17 08:02",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=SFG16-I71-75Y2"
        }
      ],
      "mtm": "SFG16-I71-75Y2",
      "productId": "9483273252",
      "itemId": "28237319655",
      "vendorItemId": "95190959758",
      "category": "Notebook",
      "srp": 1829000
    },
    {
      "storage": "512GB",
      "display": "Swift Go 16 AI",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1439000,
          "instantDiscount": 0,
          "couponDiscount": 30000,
          "cardDiscount": 80520,
          "finalPrice": 1328480,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "A",
          "confidenceText": "정확 Item ID의 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9573633117?itemId=28714706401&vendorItemId=95655361668",
          "cardEvidenceSource": null,
          "availabilityCheckedAt": "2026-09-17 16:49",
          "srp": 1439000,
          "observedListPrice": 1439000,
          "preCardPrice": 1409000,
          "priceBasisType": "crossed-out",
          "cardBenefitStatus": "captured",
          "cardRate": 6,
          "cardMaxDiscount": 80520,
          "cardProviders": [
            "NH농협",
            "BC",
            "하나"
          ],
          "cardBenefitText": "최대 6% 카드 즉시할인 (BC, NH농협, 하나)",
          "checkoutDiscountStatus": "captured",
          "checkoutDiscountReason": "total-matched-one-or-more-labels-omitted",
          "wowInstantDiscount": 30000,
          "wowCouponDiscount": 0,
          "checkoutDiscountCheckedAt": "2026-09-17T07:48:19.007Z",
          "alertEligible": true,
          "priceCheckedAt": "2026-09-17 16:49",
          "checkoutCouponDiscount": 0
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "phcnc",
          "status": "판매중",
          "displayPrice": 1400000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1400000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 1439000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1439000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "판매중",
          "displayPrice": 1460750,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1460750,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "판매중",
          "displayPrice": 1460750,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1460750,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "하이마트",
          "status": "판매중",
          "displayPrice": 1528990,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1528990,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 1693370,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1693370,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "노트마켓씨엔씨",
          "status": "판매중",
          "displayPrice": 1250000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1250000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 1400000,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-17 08:02",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=SFG16-74-70E9"
        }
      ],
      "mtm": "SFG16-74-70E9",
      "productId": "9573633117",
      "itemId": "28714706401",
      "vendorItemId": "95655361668",
      "category": "Notebook",
      "srp": 1439000
    },
    {
      "storage": "512GB",
      "display": "Swift 16 AI",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 2369000,
          "instantDiscount": 0,
          "couponDiscount": 0,
          "cardDiscount": 0,
          "finalPrice": 2369000,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "A",
          "confidenceText": "정확 Item ID의 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9437677217?itemId=28067081535&vendorItemId=95023756227",
          "cardEvidenceSource": null,
          "availabilityCheckedAt": "2026-09-17 16:49",
          "srp": 2369000,
          "observedListPrice": 2369000,
          "preCardPrice": 2369000,
          "priceBasisType": "top-visible",
          "cardBenefitStatus": "none",
          "cardRate": null,
          "cardMaxDiscount": null,
          "cardProviders": [],
          "cardBenefitText": "",
          "checkoutDiscountStatus": "missing",
          "checkoutDiscountReason": "checkout-discount-label-missing",
          "wowInstantDiscount": null,
          "wowCouponDiscount": null,
          "checkoutDiscountCheckedAt": "",
          "alertEligible": true,
          "priceCheckedAt": "2026-09-17 16:49",
          "checkoutCouponDiscount": null
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 2369000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2369000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=107769113"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "phcnc",
          "status": "판매중",
          "displayPrice": 2510000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2510000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=107769113"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "바른컴",
          "status": "판매중",
          "displayPrice": 2090000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2090000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-17 16:49",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 실시간 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=107769113"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 2159000,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-17 08:02",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=107769113"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=SF16-71T-7475"
        }
      ],
      "mtm": "SF16-71T-7475",
      "productId": "9437677217",
      "itemId": "28067081535",
      "vendorItemId": "95023756227",
      "category": "Notebook",
      "srp": 2369000
    }
  ]
};
