window.MARKET_DATA = {
  "meta": {
    "snapshotAt": "2026-09-14T13:27:15+09:00",
    "sourceFile": "아쎄르_수정.xlsx",
    "comparisonBasis": "정확한 MTM·용량이 일치하는 개별 상품 페이지의 공개 판매가와 배송비 기준",
    "exclusions": "개인화 쿠폰, 카드사별 혜택, 적립금, 로그인 전용 와우 최대혜택은 기본 비교가에서 제외",
    "monitoring": {
      "enabled": true,
      "quickWatch": "매일 10:00 KST",
      "fullResearch": "기본+정밀 동시 실행",
      "dashboardSync": "GitHub Pages 자동 반영",
      "lastAttemptAt": "2026-09-14T13:20:00+09:00",
      "lastAttemptStatus": "success",
      "lastAttemptText": "Acer Chrome 현재가 10/10 확인 · GitHub 경쟁가 0/10 확인",
      "collectionRoute": "Windows PC · 일반 Chrome 확장프로그램",
      "competitionLastAttemptAt": "2026-09-14T13:27:15+09:00"
    }
  },
  "products": [
    {
      "storage": "1TB",
      "display": "Nitro V 16",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1558000,
          "instantDiscount": null,
          "couponDiscount": 171010,
          "cardDiscount": null,
          "finalPrice": 1477990,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-14 13:14",
          "confidence": "A",
          "confidenceText": "동일 Item ID의 일반 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9573633117?itemId=28575928128&vendorItemId=95520178041",
          "availabilityCheckedAt": "2026-09-14 13:14",
          "srp": 1558000,
          "observedListPrice": 1649000,
          "priceCheckedAt": "2026-09-14 13:14"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 1665280,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1665280,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:14",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "판매중",
          "displayPrice": 1665290,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1665290,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:14",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "판매중",
          "displayPrice": 1665290,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1665290,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:14",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "롯데ON",
          "status": "판매중",
          "displayPrice": 1670380,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1670380,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:14",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 1878000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1878000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:14",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "슈프림컴",
          "status": "판매중",
          "displayPrice": 1880000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1880000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:14",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "스마일컴",
          "status": "판매중",
          "displayPrice": 1648000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1648000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:14",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 1665610,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-14 13:27",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=122672194"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=ANV16-I31-514Z"
        }
      ],
      "mtm": "ANV16-I31-514Z",
      "productId": "9573633117",
      "itemId": "28575928128",
      "vendorItemId": "95520178041",
      "category": "Notebook",
      "skuid": "74357773",
      "srp": 1558000
    },
    {
      "storage": "512GB",
      "display": "Aspire Go 14",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1429000,
          "instantDiscount": 140000,
          "couponDiscount": 30000,
          "cardDiscount": null,
          "finalPrice": 1259000,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-14 13:15",
          "confidence": "A",
          "confidenceText": "동일 Item ID의 일반 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9681715061?itemId=28951318769&vendorItemId=95881909514",
          "availabilityCheckedAt": "2026-09-14 13:15",
          "srp": 1429000,
          "observedListPrice": 1289000,
          "priceCheckedAt": "2026-09-14 13:15"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 1309000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1309000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:15",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "판매중",
          "displayPrice": 1413470,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1413470,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:15",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "판매중",
          "displayPrice": 1429000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1429000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:15",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 1469000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1469000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:15",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "슈프림컴",
          "status": "판매중",
          "displayPrice": 1590000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1590000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:15",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "롯데ON",
          "status": "판매중",
          "displayPrice": 1766240,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1766240,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:15",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "피씨블랙",
          "status": "판매중",
          "displayPrice": 1270000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1270000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:15",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 1309000,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-14 13:27",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=123650595"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=AG14-I71M-972S"
        }
      ],
      "mtm": "AG14-I71M-972S",
      "productId": "9681715061",
      "itemId": "28951318769",
      "vendorItemId": "95881909514",
      "category": "Notebook",
      "skuid": "77524457",
      "srp": 1429000
    },
    {
      "storage": "512GB",
      "display": "Aspire Go 14",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1569000,
          "instantDiscount": 109000,
          "couponDiscount": 71000,
          "cardDiscount": null,
          "finalPrice": 1389000,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-14 13:16",
          "confidence": "A",
          "confidenceText": "동일 Item ID의 일반 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9681715061?itemId=28951318771&vendorItemId=95881909515",
          "availabilityCheckedAt": "2026-09-14 13:16",
          "srp": 1569000,
          "observedListPrice": 1460000,
          "priceCheckedAt": "2026-09-14 13:16"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 1439000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1439000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:16",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123763381"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 1609000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1609000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:16",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123763381"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "phcnc",
          "status": "판매중",
          "displayPrice": 1630000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1630000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:16",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123763381"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "바른컴",
          "status": "판매중",
          "displayPrice": 1590000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1590000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:16",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=123763381"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 1439000,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-14 13:27",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=123763381"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=AG14-I71M-96C5"
        }
      ],
      "mtm": "AG14-I71M-96C5",
      "productId": "9681715061",
      "itemId": "28951318771",
      "vendorItemId": "95881909515",
      "category": "Notebook",
      "skuid": "77524458",
      "srp": 1569000
    },
    {
      "storage": "1TB",
      "display": "Predator Helios Neo 16S",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 4099000,
          "instantDiscount": 850000,
          "couponDiscount": 216570,
          "cardDiscount": null,
          "finalPrice": 3032430,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-14 13:16",
          "confidence": "A",
          "confidenceText": "동일 Item ID의 일반 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9573633117?itemId=26004597899&vendorItemId=92986675922",
          "availabilityCheckedAt": "2026-09-14 13:16",
          "srp": 4099000,
          "observedListPrice": 3249000,
          "priceCheckedAt": "2026-09-14 13:16"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 3675000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 3675000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:16",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=93445997"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "(주)두리칸",
          "status": "판매중",
          "displayPrice": 3690000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 3690000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:16",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=93445997"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "하이마트",
          "status": "판매중",
          "displayPrice": 3800640,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 3800640,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:16",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=93445997"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 3675000,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-14 13:27",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=93445997"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=PHN16S-71-949J"
        }
      ],
      "mtm": "PHN16S-71-949J",
      "productId": "9573633117",
      "itemId": "26004597899",
      "vendorItemId": "92986675922",
      "category": "Notebook",
      "skuid": "62173228",
      "srp": 4099000
    },
    {
      "storage": "512GB",
      "display": "Swift Go 14 AI",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1689000,
          "instantDiscount": 40000,
          "couponDiscount": 120000,
          "cardDiscount": null,
          "finalPrice": 1529000,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-14 13:17",
          "confidence": "A",
          "confidenceText": "동일 Item ID의 일반 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9616664363?itemId=28714706385&vendorItemId=95655361667",
          "availabilityCheckedAt": "2026-09-14 13:17",
          "srp": 1689000,
          "observedListPrice": 1649000,
          "priceCheckedAt": "2026-09-14 13:17"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 1559000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1559000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:17",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "슈프림컴",
          "status": "판매중",
          "displayPrice": 1689000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1689000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:17",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "판매중",
          "displayPrice": 1715800,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1715800,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:17",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "판매중",
          "displayPrice": 1715800,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1715800,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:17",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 1945200,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1945200,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:17",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "하이마트",
          "status": "판매중",
          "displayPrice": 1969000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1969000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:17",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "노트캐슬",
          "status": "판매중",
          "displayPrice": 1470000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1470000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:17",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 1559000,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-14 13:27",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=122719782"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=SFG14-I71-57P5"
        }
      ],
      "mtm": "SFG14-I71-57P5",
      "productId": "9616664363",
      "itemId": "28714706385",
      "vendorItemId": "95655361667",
      "category": "Notebook",
      "skuid": "75574102",
      "srp": 1689000
    },
    {
      "storage": "1TB",
      "display": "Swift Go 14 AI",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1229000,
          "instantDiscount": 130000,
          "couponDiscount": 0,
          "cardDiscount": null,
          "finalPrice": 1099000,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-14 13:18",
          "confidence": "A",
          "confidenceText": "동일 Item ID의 일반 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9428079675?itemId=28287192873&vendorItemId=95240133006",
          "availabilityCheckedAt": "2026-09-14 13:18",
          "srp": 1229000,
          "observedListPrice": 1099000,
          "priceCheckedAt": "2026-09-14 13:18"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 1358460,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1358460,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:18",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "판매중",
          "displayPrice": 1358470,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1358470,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:18",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "판매중",
          "displayPrice": 1358470,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1358470,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:18",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "롯데ON",
          "status": "판매중",
          "displayPrice": 1359000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1359000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:18",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "KTG",
          "status": "판매중",
          "displayPrice": 1368990,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1368990,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:18",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "신세계컴",
          "status": "판매중",
          "displayPrice": 1208000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1208000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:18",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 1358790,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-14 13:27",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=122636128"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=SFG14-75-508U"
        }
      ],
      "mtm": "SFG14-75-508U",
      "productId": "9428079675",
      "itemId": "28287192873",
      "vendorItemId": "95240133006",
      "category": "Notebook",
      "skuid": "72157300",
      "srp": 1229000
    },
    {
      "storage": "1TB",
      "display": "Swift Go 16 AI · 리퍼비시",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1659000,
          "instantDiscount": null,
          "couponDiscount": 38900,
          "cardDiscount": null,
          "finalPrice": 2260100,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-14 13:18",
          "confidence": "A",
          "confidenceText": "동일 Item ID의 일반 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9573633117?itemId=28029585486&vendorItemId=94986693706",
          "availabilityCheckedAt": "2026-09-14 13:18",
          "srp": 1659000,
          "observedListPrice": 2299000,
          "priceCheckedAt": "2026-09-14 13:18"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 1808080,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1808080,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:18",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122702450"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 1808080,
          "condition": "정확한 MTM 상품 페이지가 현재 일시 품절",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-14 13:27",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=122702450"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=SFG16-74-7412"
        }
      ],
      "mtm": "SFG16-74-7412",
      "productId": "9573633117",
      "itemId": "28029585486",
      "vendorItemId": "94986693706",
      "category": "Notebook",
      "skuid": "70646376",
      "srp": 1659000
    },
    {
      "storage": "1TB",
      "display": "Swift Go 16 AI",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1829000,
          "instantDiscount": 130000,
          "couponDiscount": 20000,
          "cardDiscount": null,
          "finalPrice": 1679000,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-14 13:19",
          "confidence": "A",
          "confidenceText": "동일 Item ID의 일반 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9483273252?itemId=28237319655&vendorItemId=95190959758",
          "availabilityCheckedAt": "2026-09-14 13:19",
          "srp": 1829000,
          "observedListPrice": 1699000,
          "priceCheckedAt": "2026-09-14 13:19"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "슈프림컴",
          "status": "판매중",
          "displayPrice": 2365000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2365000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:19",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "판매중",
          "displayPrice": 2398450,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2398450,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:19",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "판매중",
          "displayPrice": 2398450,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2398450,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:19",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 2398460,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2398460,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:19",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 2399000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2399000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:19",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "롯데ON",
          "status": "판매중",
          "displayPrice": 2785560,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2785560,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:19",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "노트캐슬",
          "status": "판매중",
          "displayPrice": 2040000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2040000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:19",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 2365000,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-14 13:27",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=122636236"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=SFG16-I71-75Y2"
        }
      ],
      "mtm": "SFG16-I71-75Y2",
      "productId": "9483273252",
      "itemId": "28237319655",
      "vendorItemId": "95190959758",
      "category": "Notebook",
      "skuid": "71847372",
      "srp": 1829000
    },
    {
      "storage": "512GB",
      "display": "Swift Go 16 AI",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 1439000,
          "instantDiscount": 150000,
          "couponDiscount": 0,
          "cardDiscount": null,
          "finalPrice": 1289000,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-14 13:20",
          "confidence": "A",
          "confidenceText": "동일 Item ID의 일반 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9573633117?itemId=28714706401&vendorItemId=95655361668",
          "availabilityCheckedAt": "2026-09-14 13:20",
          "srp": 1439000,
          "observedListPrice": 1289000,
          "priceCheckedAt": "2026-09-14 13:20"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 1319000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1319000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:20",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "phcnc",
          "status": "판매중",
          "displayPrice": 1400000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1400000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:20",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "판매중",
          "displayPrice": 1460750,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1460750,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:20",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "판매중",
          "displayPrice": 1460750,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1460750,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:20",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "하이마트",
          "status": "판매중",
          "displayPrice": 1528990,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1528990,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:20",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 1693370,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1693370,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:20",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "노엘시스템",
          "status": "판매중",
          "displayPrice": 1250000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 1250000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:20",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 1400000,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-14 13:27",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=122719720"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=SFG16-74-70E9"
        }
      ],
      "mtm": "SFG16-74-70E9",
      "productId": "9573633117",
      "itemId": "28714706401",
      "vendorItemId": "95655361668",
      "category": "Notebook",
      "skuid": "75574103",
      "srp": 1439000
    },
    {
      "storage": "512GB",
      "display": "Swift 16 AI",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 2369000,
          "instantDiscount": 190000,
          "couponDiscount": 20000,
          "cardDiscount": null,
          "finalPrice": 2159000,
          "shipping": 0,
          "condition": "사용자 제공 URL의 동일 Item ID 가격만 반영",
          "sourceType": "사용자 제공 쿠팡 URL",
          "checkedAt": "2026-09-14 13:20",
          "confidence": "A",
          "confidenceText": "동일 Item ID의 일반 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9437677217?itemId=28067081535&vendorItemId=95023756227",
          "availabilityCheckedAt": "2026-09-14 13:20",
          "srp": 2369000,
          "observedListPrice": 2179000,
          "priceCheckedAt": "2026-09-14 13:20"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 2159000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2159000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:20",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=107769113"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "phcnc",
          "status": "판매중",
          "displayPrice": 2510000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2510000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:20",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=107769113"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "신세계컴",
          "status": "판매중",
          "displayPrice": 2090000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 2090000,
          "shipping": 0,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-14 13:20",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=107769113"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "다나와 최저가",
          "status": "판매처 재검증 대기",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": 2159000,
          "condition": "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
          "sourceType": "다나와 개별 상품 페이지",
          "checkedAt": "2026-09-14 13:27",
          "confidence": "C",
          "confidenceText": "동일 MTM의 개별 판매처를 확인하지 못해 비교에서 제외",
          "url": "https://prod.danawa.com/info/?pcode=107769113"
        },
        {
          "role": "competitor",
          "channel": "가격비교",
          "seller": "네이버쇼핑 검색",
          "status": "조사 중",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "정확한 MTM과 용량 일치 여부 자동 확인 대기",
          "sourceType": "네이버쇼핑 검색",
          "checkedAt": "미확인",
          "confidence": "C",
          "confidenceText": "초기 검증 대기",
          "url": "https://search.shopping.naver.com/search/all?query=SF16-71T-7475"
        }
      ],
      "mtm": "SF16-71T-7475",
      "productId": "9437677217",
      "itemId": "28067081535",
      "vendorItemId": "95023756227",
      "category": "Notebook",
      "skuid": "70743710",
      "srp": 2369000
    }
  ]
};
