window.MARKET_DATA = {
    "meta":  {
                 "snapshotAt":  "2026-09-11T16:29:17+09:00",
                 "sourceFile":  "아쎄르_수정.xlsx",
                 "comparisonBasis":  "정확한 MTM·용량이 일치하는 개별 상품 페이지의 공개 판매가와 배송비 기준",
                 "exclusions":  "개인화 쿠폰, 카드사별 혜택, 적립금, 로그인 전용 와우 최대혜택은 기본 비교가에서 제외",
                 "monitoring":  {
                                    "enabled":  true,
                                    "quickWatch":  "留ㅼ씪 11:30 KST",
                                    "fullResearch":  "기본+정밀 동시 실행",
                                    "dashboardSync":  "GitHub Pages 자동 반영",
                                    "lastAttemptAt":  "2026-09-11T16:29:17+09:00",
                                    "lastAttemptStatus":  "success",
                                    "lastAttemptText":  "Acer ?쇰컲 Chrome 議곗궗 쨌 ?꾩옱媛 ?뺤씤 10/10",
                                    "collectionRoute":  "Windows PC 쨌 ?쇰컲 Chrome ?뺤옣?꾨줈洹몃옩"
                                }
             },
    "products":  [
                     {
                         "mtm":  "ANV16-I31-514Z",
                         "storage":  "1TB",
                         "display":  "Nitro V 16",
                         "productId":  "9573633117",
                         "itemId":  "28575928128",
                         "vendorItemId":  "95520178041",
                         "validation":  "identifiers-verified",
                         "offers":  [
                                        {
                                            "role":  "mine",
                                            "channel":  "쿠팡",
                                            "seller":  "내 쿠팡 상품",
                                            "status":  "?꾩옱媛 吏곸젒 ?뺤씤",
                                            "displayPrice":  1330190,
                                            "instantDiscount":  null,
                                            "couponDiscount":  null,
                                            "cardDiscount":  null,
                                            "finalPrice":  1330190,
                                            "shipping":  0,
                                            "condition":  "사용자 제공 URL의 동일 Item ID 가격만 반영",
                                            "sourceType":  "사용자 제공 쿠팡 URL",
                                            "checkedAt":  "2026-09-11 16:58",
                                            "confidence":  "A",
                                            "confidenceText":  "?숈씪 Item ID???쇰컲 Chrome ?붾㈃?먯꽌 媛寃??뺤씤",
                                            "url":  "https://www.coupang.com/vp/products/9573633117?itemId=28575928128\u0026vendorItemId=95520178041",
                                            "availabilityCheckedAt":  "2026-09-11 16:58",
                                            "priceCheckedAt":  "2026-09-11 16:58"
                                        },
                                        {
                                            "role":  "competitor",
                                            "channel":  "가격비교",
                                            "seller":  "다나와 최저가",
                                            "status":  "현재가 확인",
                                            "displayPrice":  1665620,
                                            "finalPrice":  1665620,
                                            "referencePrice":  1665620,
                                            "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                            "sourceType":  "다나와 개별 상품 페이지",
                                            "checkedAt":  "2026-09-11 16:29",
                                            "confidence":  "B",
                                            "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                            "url":  "https://prod.danawa.com/info/?pcode=122672194"
                                        }
                                    ],
                         "references":  [
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "다나와 최저가",
                                                "status":  "현재가 확인",
                                                "displayPrice":  1665620,
                                                "finalPrice":  1665620,
                                                "referencePrice":  1665620,
                                                "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                                "sourceType":  "다나와 개별 상품 페이지",
                                                "checkedAt":  "2026-09-11 16:29",
                                                "confidence":  "B",
                                                "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                                "url":  "https://prod.danawa.com/info/?pcode=122672194"
                                            },
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "네이버쇼핑 검색",
                                                "status":  "조사 중",
                                                "displayPrice":  null,
                                                "finalPrice":  null,
                                                "referencePrice":  null,
                                                "condition":  "정확한 MTM과 용량 일치 여부 자동 확인 대기",
                                                "sourceType":  "네이버쇼핑 검색",
                                                "checkedAt":  "미확인",
                                                "confidence":  "C",
                                                "confidenceText":  "초기 검증 대기",
                                                "url":  "https://search.shopping.naver.com/search/all?query=ANV16-I31-514Z"
                                            }
                                        ]
                     },
                     {
                         "mtm":  "AG14-I71M-972S",
                         "storage":  "512GB",
                         "display":  "Aspire Go 14",
                         "productId":  "9681715061",
                         "itemId":  "28951318769",
                         "vendorItemId":  "95881909514",
                         "validation":  "identifiers-verified",
                         "offers":  [
                                        {
                                            "role":  "mine",
                                            "channel":  "쿠팡",
                                            "seller":  "내 쿠팡 상품",
                                            "status":  "?꾩옱媛 吏곸젒 ?뺤씤",
                                            "displayPrice":  1259000,
                                            "instantDiscount":  null,
                                            "couponDiscount":  null,
                                            "cardDiscount":  null,
                                            "finalPrice":  1259000,
                                            "shipping":  0,
                                            "condition":  "사용자 제공 URL의 동일 Item ID 가격만 반영",
                                            "sourceType":  "사용자 제공 쿠팡 URL",
                                            "checkedAt":  "2026-09-11 16:59",
                                            "confidence":  "A",
                                            "confidenceText":  "?숈씪 Item ID???쇰컲 Chrome ?붾㈃?먯꽌 媛寃??뺤씤",
                                            "url":  "https://www.coupang.com/vp/products/9681715061?itemId=28951318769\u0026vendorItemId=95881909514",
                                            "availabilityCheckedAt":  "2026-09-11 16:59",
                                            "priceCheckedAt":  "2026-09-11 16:59"
                                        },
                                        {
                                            "role":  "competitor",
                                            "channel":  "가격비교",
                                            "seller":  "다나와 최저가",
                                            "status":  "현재가 확인",
                                            "displayPrice":  1309000,
                                            "finalPrice":  1309000,
                                            "referencePrice":  1309000,
                                            "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                            "sourceType":  "다나와 개별 상품 페이지",
                                            "checkedAt":  "2026-09-11 16:29",
                                            "confidence":  "B",
                                            "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                            "url":  "https://prod.danawa.com/info/?pcode=123650595"
                                        }
                                    ],
                         "references":  [
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "다나와 최저가",
                                                "status":  "현재가 확인",
                                                "displayPrice":  1309000,
                                                "finalPrice":  1309000,
                                                "referencePrice":  1309000,
                                                "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                                "sourceType":  "다나와 개별 상품 페이지",
                                                "checkedAt":  "2026-09-11 16:29",
                                                "confidence":  "B",
                                                "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                                "url":  "https://prod.danawa.com/info/?pcode=123650595"
                                            },
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "네이버쇼핑 검색",
                                                "status":  "조사 중",
                                                "displayPrice":  null,
                                                "finalPrice":  null,
                                                "referencePrice":  null,
                                                "condition":  "정확한 MTM과 용량 일치 여부 자동 확인 대기",
                                                "sourceType":  "네이버쇼핑 검색",
                                                "checkedAt":  "미확인",
                                                "confidence":  "C",
                                                "confidenceText":  "초기 검증 대기",
                                                "url":  "https://search.shopping.naver.com/search/all?query=AG14-I71M-972S"
                                            }
                                        ]
                     },
                     {
                         "mtm":  "AG14-I71M-96C5",
                         "storage":  "512GB",
                         "display":  "Aspire Go 14",
                         "productId":  "9681715061",
                         "itemId":  "28951318771",
                         "vendorItemId":  "95881909515",
                         "validation":  "identifiers-verified",
                         "offers":  [
                                        {
                                            "role":  "mine",
                                            "channel":  "쿠팡",
                                            "seller":  "내 쿠팡 상품",
                                            "status":  "?꾩옱媛 吏곸젒 ?뺤씤",
                                            "displayPrice":  1389000,
                                            "instantDiscount":  null,
                                            "couponDiscount":  null,
                                            "cardDiscount":  null,
                                            "finalPrice":  1389000,
                                            "shipping":  0,
                                            "condition":  "사용자 제공 URL의 동일 Item ID 가격만 반영",
                                            "sourceType":  "사용자 제공 쿠팡 URL",
                                            "checkedAt":  "2026-09-11 16:59",
                                            "confidence":  "A",
                                            "confidenceText":  "?숈씪 Item ID???쇰컲 Chrome ?붾㈃?먯꽌 媛寃??뺤씤",
                                            "url":  "https://www.coupang.com/vp/products/9681715061?itemId=28951318771\u0026vendorItemId=95881909515",
                                            "availabilityCheckedAt":  "2026-09-11 16:59",
                                            "priceCheckedAt":  "2026-09-11 16:59"
                                        },
                                        {
                                            "role":  "competitor",
                                            "channel":  "가격비교",
                                            "seller":  "다나와 최저가",
                                            "status":  "현재가 확인",
                                            "displayPrice":  1439000,
                                            "finalPrice":  1439000,
                                            "referencePrice":  1439000,
                                            "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                            "sourceType":  "다나와 개별 상품 페이지",
                                            "checkedAt":  "2026-09-11 16:29",
                                            "confidence":  "B",
                                            "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                            "url":  "https://prod.danawa.com/info/?pcode=123763381"
                                        }
                                    ],
                         "references":  [
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "다나와 최저가",
                                                "status":  "현재가 확인",
                                                "displayPrice":  1439000,
                                                "finalPrice":  1439000,
                                                "referencePrice":  1439000,
                                                "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                                "sourceType":  "다나와 개별 상품 페이지",
                                                "checkedAt":  "2026-09-11 16:29",
                                                "confidence":  "B",
                                                "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                                "url":  "https://prod.danawa.com/info/?pcode=123763381"
                                            },
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "네이버쇼핑 검색",
                                                "status":  "조사 중",
                                                "displayPrice":  null,
                                                "finalPrice":  null,
                                                "referencePrice":  null,
                                                "condition":  "정확한 MTM과 용량 일치 여부 자동 확인 대기",
                                                "sourceType":  "네이버쇼핑 검색",
                                                "checkedAt":  "미확인",
                                                "confidence":  "C",
                                                "confidenceText":  "초기 검증 대기",
                                                "url":  "https://search.shopping.naver.com/search/all?query=AG14-I71M-96C5"
                                            }
                                        ]
                     },
                     {
                         "mtm":  "PHN16S-71-949J",
                         "storage":  "1TB",
                         "display":  "Predator Helios Neo 16S",
                         "productId":  "9573633117",
                         "itemId":  "26004597899",
                         "vendorItemId":  "92986675922",
                         "validation":  "identifiers-verified",
                         "offers":  [
                                        {
                                            "role":  "mine",
                                            "channel":  "쿠팡",
                                            "seller":  "내 쿠팡 상품",
                                            "status":  "?꾩옱媛 吏곸젒 ?뺤씤",
                                            "displayPrice":  3032430,
                                            "instantDiscount":  null,
                                            "couponDiscount":  null,
                                            "cardDiscount":  null,
                                            "finalPrice":  3032430,
                                            "shipping":  0,
                                            "condition":  "사용자 제공 URL의 동일 Item ID 가격만 반영",
                                            "sourceType":  "사용자 제공 쿠팡 URL",
                                            "checkedAt":  "2026-09-11 16:59",
                                            "confidence":  "A",
                                            "confidenceText":  "?숈씪 Item ID???쇰컲 Chrome ?붾㈃?먯꽌 媛寃??뺤씤",
                                            "url":  "https://www.coupang.com/vp/products/9573633117?itemId=26004597899\u0026vendorItemId=92986675922",
                                            "availabilityCheckedAt":  "2026-09-11 16:59",
                                            "priceCheckedAt":  "2026-09-11 16:59"
                                        },
                                        {
                                            "role":  "competitor",
                                            "channel":  "가격비교",
                                            "seller":  "다나와 최저가",
                                            "status":  "현재가 확인",
                                            "displayPrice":  3675000,
                                            "finalPrice":  3675000,
                                            "referencePrice":  3675000,
                                            "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                            "sourceType":  "다나와 개별 상품 페이지",
                                            "checkedAt":  "2026-09-11 16:29",
                                            "confidence":  "B",
                                            "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                            "url":  "https://prod.danawa.com/info/?pcode=93445997"
                                        }
                                    ],
                         "references":  [
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "다나와 최저가",
                                                "status":  "현재가 확인",
                                                "displayPrice":  3675000,
                                                "finalPrice":  3675000,
                                                "referencePrice":  3675000,
                                                "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                                "sourceType":  "다나와 개별 상품 페이지",
                                                "checkedAt":  "2026-09-11 16:29",
                                                "confidence":  "B",
                                                "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                                "url":  "https://prod.danawa.com/info/?pcode=93445997"
                                            },
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "네이버쇼핑 검색",
                                                "status":  "조사 중",
                                                "displayPrice":  null,
                                                "finalPrice":  null,
                                                "referencePrice":  null,
                                                "condition":  "정확한 MTM과 용량 일치 여부 자동 확인 대기",
                                                "sourceType":  "네이버쇼핑 검색",
                                                "checkedAt":  "미확인",
                                                "confidence":  "C",
                                                "confidenceText":  "초기 검증 대기",
                                                "url":  "https://search.shopping.naver.com/search/all?query=PHN16S-71-949J"
                                            }
                                        ]
                     },
                     {
                         "mtm":  "SFG14-I71-57P5",
                         "storage":  "512GB",
                         "display":  "Swift Go 14 AI",
                         "productId":  "9616664363",
                         "itemId":  "28714706385",
                         "vendorItemId":  "95655361667",
                         "validation":  "identifiers-verified",
                         "offers":  [
                                        {
                                            "role":  "mine",
                                            "channel":  "쿠팡",
                                            "seller":  "내 쿠팡 상품",
                                            "status":  "?꾩옱媛 吏곸젒 ?뺤씤",
                                            "displayPrice":  1529000,
                                            "instantDiscount":  null,
                                            "couponDiscount":  null,
                                            "cardDiscount":  null,
                                            "finalPrice":  1529000,
                                            "shipping":  0,
                                            "condition":  "사용자 제공 URL의 동일 Item ID 가격만 반영",
                                            "sourceType":  "사용자 제공 쿠팡 URL",
                                            "checkedAt":  "2026-09-11 17:00",
                                            "confidence":  "A",
                                            "confidenceText":  "?숈씪 Item ID???쇰컲 Chrome ?붾㈃?먯꽌 媛寃??뺤씤",
                                            "url":  "https://www.coupang.com/vp/products/9616664363?itemId=28714706385\u0026vendorItemId=95655361667",
                                            "availabilityCheckedAt":  "2026-09-11 17:00",
                                            "priceCheckedAt":  "2026-09-11 17:00"
                                        },
                                        {
                                            "role":  "competitor",
                                            "channel":  "가격비교",
                                            "seller":  "다나와 최저가",
                                            "status":  "현재가 확인",
                                            "displayPrice":  1559000,
                                            "finalPrice":  1559000,
                                            "referencePrice":  1559000,
                                            "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                            "sourceType":  "다나와 개별 상품 페이지",
                                            "checkedAt":  "2026-09-11 16:29",
                                            "confidence":  "B",
                                            "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                            "url":  "https://prod.danawa.com/info/?pcode=122719782"
                                        }
                                    ],
                         "references":  [
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "다나와 최저가",
                                                "status":  "현재가 확인",
                                                "displayPrice":  1559000,
                                                "finalPrice":  1559000,
                                                "referencePrice":  1559000,
                                                "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                                "sourceType":  "다나와 개별 상품 페이지",
                                                "checkedAt":  "2026-09-11 16:29",
                                                "confidence":  "B",
                                                "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                                "url":  "https://prod.danawa.com/info/?pcode=122719782"
                                            },
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "네이버쇼핑 검색",
                                                "status":  "조사 중",
                                                "displayPrice":  null,
                                                "finalPrice":  null,
                                                "referencePrice":  null,
                                                "condition":  "정확한 MTM과 용량 일치 여부 자동 확인 대기",
                                                "sourceType":  "네이버쇼핑 검색",
                                                "checkedAt":  "미확인",
                                                "confidence":  "C",
                                                "confidenceText":  "초기 검증 대기",
                                                "url":  "https://search.shopping.naver.com/search/all?query=SFG14-I71-57P5"
                                            }
                                        ]
                     },
                     {
                         "mtm":  "SFG14-75-508U",
                         "storage":  "1TB",
                         "display":  "Swift Go 14 AI",
                         "productId":  "9428079675",
                         "itemId":  "28287192873",
                         "vendorItemId":  "95240133006",
                         "validation":  "identifiers-verified",
                         "offers":  [
                                        {
                                            "role":  "mine",
                                            "channel":  "쿠팡",
                                            "seller":  "내 쿠팡 상품",
                                            "status":  "?꾩옱媛 吏곸젒 ?뺤씤",
                                            "displayPrice":  1079100,
                                            "instantDiscount":  null,
                                            "couponDiscount":  null,
                                            "cardDiscount":  null,
                                            "finalPrice":  1079100,
                                            "shipping":  0,
                                            "condition":  "사용자 제공 URL의 동일 Item ID 가격만 반영",
                                            "sourceType":  "사용자 제공 쿠팡 URL",
                                            "checkedAt":  "2026-09-11 17:00",
                                            "confidence":  "A",
                                            "confidenceText":  "?숈씪 Item ID???쇰컲 Chrome ?붾㈃?먯꽌 媛寃??뺤씤",
                                            "url":  "https://www.coupang.com/vp/products/9428079675?itemId=28287192873\u0026vendorItemId=95240133006",
                                            "availabilityCheckedAt":  "2026-09-11 17:00",
                                            "priceCheckedAt":  "2026-09-11 17:00"
                                        },
                                        {
                                            "role":  "competitor",
                                            "channel":  "가격비교",
                                            "seller":  "다나와 최저가",
                                            "status":  "현재가 확인",
                                            "displayPrice":  1358800,
                                            "finalPrice":  1358800,
                                            "referencePrice":  1358800,
                                            "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                            "sourceType":  "다나와 개별 상품 페이지",
                                            "checkedAt":  "2026-09-11 16:29",
                                            "confidence":  "B",
                                            "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                            "url":  "https://prod.danawa.com/info/?pcode=122636128"
                                        }
                                    ],
                         "references":  [
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "다나와 최저가",
                                                "status":  "현재가 확인",
                                                "displayPrice":  1358800,
                                                "finalPrice":  1358800,
                                                "referencePrice":  1358800,
                                                "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                                "sourceType":  "다나와 개별 상품 페이지",
                                                "checkedAt":  "2026-09-11 16:29",
                                                "confidence":  "B",
                                                "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                                "url":  "https://prod.danawa.com/info/?pcode=122636128"
                                            },
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "네이버쇼핑 검색",
                                                "status":  "조사 중",
                                                "displayPrice":  null,
                                                "finalPrice":  null,
                                                "referencePrice":  null,
                                                "condition":  "정확한 MTM과 용량 일치 여부 자동 확인 대기",
                                                "sourceType":  "네이버쇼핑 검색",
                                                "checkedAt":  "미확인",
                                                "confidence":  "C",
                                                "confidenceText":  "초기 검증 대기",
                                                "url":  "https://search.shopping.naver.com/search/all?query=SFG14-75-508U"
                                            }
                                        ]
                     },
                     {
                         "mtm":  "SFG16-74-7412",
                         "storage":  "1TB",
                         "display":  "Swift Go 16 AI · 리퍼비시",
                         "productId":  "9573633117",
                         "itemId":  "28029585486",
                         "vendorItemId":  "94986693706",
                         "validation":  "identifiers-verified",
                         "offers":  [
                                        {
                                            "role":  "mine",
                                            "channel":  "쿠팡",
                                            "seller":  "내 쿠팡 상품",
                                            "status":  "?꾩옱媛 吏곸젒 ?뺤씤",
                                            "displayPrice":  2260100,
                                            "instantDiscount":  null,
                                            "couponDiscount":  null,
                                            "cardDiscount":  null,
                                            "finalPrice":  2260100,
                                            "shipping":  0,
                                            "condition":  "사용자 제공 URL의 동일 Item ID 가격만 반영",
                                            "sourceType":  "사용자 제공 쿠팡 URL",
                                            "checkedAt":  "2026-09-11 17:00",
                                            "confidence":  "A",
                                            "confidenceText":  "?숈씪 Item ID???쇰컲 Chrome ?붾㈃?먯꽌 媛寃??뺤씤",
                                            "url":  "https://www.coupang.com/vp/products/9573633117?itemId=28029585486\u0026vendorItemId=94986693706",
                                            "availabilityCheckedAt":  "2026-09-11 17:00",
                                            "priceCheckedAt":  "2026-09-11 17:00"
                                        },
                                        {
                                            "role":  "competitor",
                                            "channel":  "가격비교",
                                            "seller":  "다나와 최저가",
                                            "status":  "현재가 확인",
                                            "displayPrice":  1808080,
                                            "finalPrice":  1808080,
                                            "referencePrice":  1808080,
                                            "condition":  "정확한 MTM 상품 페이지가 현재 일시 품절",
                                            "sourceType":  "다나와 개별 상품 페이지",
                                            "checkedAt":  "2026-09-11 16:29",
                                            "confidence":  "B",
                                            "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                            "url":  "https://prod.danawa.com/info/?pcode=122702450"
                                        }
                                    ],
                         "references":  [
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "다나와 최저가",
                                                "status":  "현재가 확인",
                                                "displayPrice":  1808080,
                                                "finalPrice":  1808080,
                                                "referencePrice":  1808080,
                                                "condition":  "정확한 MTM 상품 페이지가 현재 일시 품절",
                                                "sourceType":  "다나와 개별 상품 페이지",
                                                "checkedAt":  "2026-09-11 16:29",
                                                "confidence":  "B",
                                                "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                                "url":  "https://prod.danawa.com/info/?pcode=122702450"
                                            },
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "네이버쇼핑 검색",
                                                "status":  "조사 중",
                                                "displayPrice":  null,
                                                "finalPrice":  null,
                                                "referencePrice":  null,
                                                "condition":  "정확한 MTM과 용량 일치 여부 자동 확인 대기",
                                                "sourceType":  "네이버쇼핑 검색",
                                                "checkedAt":  "미확인",
                                                "confidence":  "C",
                                                "confidenceText":  "초기 검증 대기",
                                                "url":  "https://search.shopping.naver.com/search/all?query=SFG16-74-7412"
                                            }
                                        ]
                     },
                     {
                         "mtm":  "SFG16-I71-75Y2",
                         "storage":  "1TB",
                         "display":  "Swift Go 16 AI",
                         "productId":  "9483273252",
                         "itemId":  "28237319655",
                         "vendorItemId":  "95190959758",
                         "validation":  "identifiers-verified",
                         "offers":  [
                                        {
                                            "role":  "mine",
                                            "channel":  "쿠팡",
                                            "seller":  "내 쿠팡 상품",
                                            "status":  "?꾩옱媛 吏곸젒 ?뺤씤",
                                            "displayPrice":  1679000,
                                            "instantDiscount":  null,
                                            "couponDiscount":  null,
                                            "cardDiscount":  null,
                                            "finalPrice":  1679000,
                                            "shipping":  0,
                                            "condition":  "사용자 제공 URL의 동일 Item ID 가격만 반영",
                                            "sourceType":  "사용자 제공 쿠팡 URL",
                                            "checkedAt":  "2026-09-11 17:01",
                                            "confidence":  "A",
                                            "confidenceText":  "?숈씪 Item ID???쇰컲 Chrome ?붾㈃?먯꽌 媛寃??뺤씤",
                                            "url":  "https://www.coupang.com/vp/products/9483273252?itemId=28237319655\u0026vendorItemId=95190959758",
                                            "availabilityCheckedAt":  "2026-09-11 17:01",
                                            "priceCheckedAt":  "2026-09-11 17:01"
                                        },
                                        {
                                            "role":  "competitor",
                                            "channel":  "가격비교",
                                            "seller":  "다나와 최저가",
                                            "status":  "현재가 확인",
                                            "displayPrice":  2365000,
                                            "finalPrice":  2365000,
                                            "referencePrice":  2365000,
                                            "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                            "sourceType":  "다나와 개별 상품 페이지",
                                            "checkedAt":  "2026-09-11 16:29",
                                            "confidence":  "B",
                                            "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                            "url":  "https://prod.danawa.com/info/?pcode=122636236"
                                        }
                                    ],
                         "references":  [
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "다나와 최저가",
                                                "status":  "현재가 확인",
                                                "displayPrice":  2365000,
                                                "finalPrice":  2365000,
                                                "referencePrice":  2365000,
                                                "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                                "sourceType":  "다나와 개별 상품 페이지",
                                                "checkedAt":  "2026-09-11 16:29",
                                                "confidence":  "B",
                                                "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                                "url":  "https://prod.danawa.com/info/?pcode=122636236"
                                            },
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "네이버쇼핑 검색",
                                                "status":  "조사 중",
                                                "displayPrice":  null,
                                                "finalPrice":  null,
                                                "referencePrice":  null,
                                                "condition":  "정확한 MTM과 용량 일치 여부 자동 확인 대기",
                                                "sourceType":  "네이버쇼핑 검색",
                                                "checkedAt":  "미확인",
                                                "confidence":  "C",
                                                "confidenceText":  "초기 검증 대기",
                                                "url":  "https://search.shopping.naver.com/search/all?query=SFG16-I71-75Y2"
                                            }
                                        ]
                     },
                     {
                         "mtm":  "SFG16-74-70E9",
                         "storage":  "512GB",
                         "display":  "Swift Go 16 AI",
                         "productId":  "9573633117",
                         "itemId":  "28714706401",
                         "vendorItemId":  "95655361668",
                         "validation":  "identifiers-verified",
                         "offers":  [
                                        {
                                            "role":  "mine",
                                            "channel":  "쿠팡",
                                            "seller":  "내 쿠팡 상품",
                                            "status":  "?꾩옱媛 吏곸젒 ?뺤씤",
                                            "displayPrice":  1289000,
                                            "instantDiscount":  null,
                                            "couponDiscount":  null,
                                            "cardDiscount":  null,
                                            "finalPrice":  1289000,
                                            "shipping":  0,
                                            "condition":  "사용자 제공 URL의 동일 Item ID 가격만 반영",
                                            "sourceType":  "사용자 제공 쿠팡 URL",
                                            "checkedAt":  "2026-09-11 17:01",
                                            "confidence":  "A",
                                            "confidenceText":  "?숈씪 Item ID???쇰컲 Chrome ?붾㈃?먯꽌 媛寃??뺤씤",
                                            "url":  "https://www.coupang.com/vp/products/9573633117?itemId=28714706401\u0026vendorItemId=95655361668",
                                            "availabilityCheckedAt":  "2026-09-11 17:01",
                                            "priceCheckedAt":  "2026-09-11 17:01"
                                        },
                                        {
                                            "role":  "competitor",
                                            "channel":  "가격비교",
                                            "seller":  "다나와 최저가",
                                            "status":  "현재가 확인",
                                            "displayPrice":  1400000,
                                            "finalPrice":  1400000,
                                            "referencePrice":  1400000,
                                            "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                            "sourceType":  "다나와 개별 상품 페이지",
                                            "checkedAt":  "2026-09-11 16:29",
                                            "confidence":  "B",
                                            "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                            "url":  "https://prod.danawa.com/info/?pcode=122719720"
                                        }
                                    ],
                         "references":  [
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "다나와 최저가",
                                                "status":  "현재가 확인",
                                                "displayPrice":  1400000,
                                                "finalPrice":  1400000,
                                                "referencePrice":  1400000,
                                                "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                                "sourceType":  "다나와 개별 상품 페이지",
                                                "checkedAt":  "2026-09-11 16:29",
                                                "confidence":  "B",
                                                "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                                "url":  "https://prod.danawa.com/info/?pcode=122719720"
                                            },
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "네이버쇼핑 검색",
                                                "status":  "조사 중",
                                                "displayPrice":  null,
                                                "finalPrice":  null,
                                                "referencePrice":  null,
                                                "condition":  "정확한 MTM과 용량 일치 여부 자동 확인 대기",
                                                "sourceType":  "네이버쇼핑 검색",
                                                "checkedAt":  "미확인",
                                                "confidence":  "C",
                                                "confidenceText":  "초기 검증 대기",
                                                "url":  "https://search.shopping.naver.com/search/all?query=SFG16-74-70E9"
                                            }
                                        ]
                     },
                     {
                         "mtm":  "SF16-71T-7475",
                         "storage":  "512GB",
                         "display":  "Swift 16 AI",
                         "productId":  "9437677217",
                         "itemId":  "28067081535",
                         "vendorItemId":  "95023756227",
                         "validation":  "identifiers-verified",
                         "offers":  [
                                        {
                                            "role":  "mine",
                                            "channel":  "쿠팡",
                                            "seller":  "내 쿠팡 상품",
                                            "status":  "?꾩옱媛 吏곸젒 ?뺤씤",
                                            "displayPrice":  2159000,
                                            "instantDiscount":  null,
                                            "couponDiscount":  null,
                                            "cardDiscount":  null,
                                            "finalPrice":  2159000,
                                            "shipping":  0,
                                            "condition":  "사용자 제공 URL의 동일 Item ID 가격만 반영",
                                            "sourceType":  "사용자 제공 쿠팡 URL",
                                            "checkedAt":  "2026-09-11 17:02",
                                            "confidence":  "A",
                                            "confidenceText":  "?숈씪 Item ID???쇰컲 Chrome ?붾㈃?먯꽌 媛寃??뺤씤",
                                            "url":  "https://www.coupang.com/vp/products/9437677217?itemId=28067081535\u0026vendorItemId=95023756227",
                                            "availabilityCheckedAt":  "2026-09-11 17:02",
                                            "priceCheckedAt":  "2026-09-11 17:02"
                                        },
                                        {
                                            "role":  "competitor",
                                            "channel":  "가격비교",
                                            "seller":  "다나와 최저가",
                                            "status":  "현재가 확인",
                                            "displayPrice":  2159000,
                                            "finalPrice":  2159000,
                                            "referencePrice":  2159000,
                                            "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                            "sourceType":  "다나와 개별 상품 페이지",
                                            "checkedAt":  "2026-09-11 16:29",
                                            "confidence":  "B",
                                            "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                            "url":  "https://prod.danawa.com/info/?pcode=107769113"
                                        }
                                    ],
                         "references":  [
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "다나와 최저가",
                                                "status":  "현재가 확인",
                                                "displayPrice":  2159000,
                                                "finalPrice":  2159000,
                                                "referencePrice":  2159000,
                                                "condition":  "정확한 MTM·용량 상품 페이지의 배송비 포함 공개 최저가",
                                                "sourceType":  "다나와 개별 상품 페이지",
                                                "checkedAt":  "2026-09-11 16:29",
                                                "confidence":  "B",
                                                "confidenceText":  "정확한 MTM과 용량을 개별 상품 페이지에서 확인",
                                                "url":  "https://prod.danawa.com/info/?pcode=107769113"
                                            },
                                            {
                                                "role":  "competitor",
                                                "channel":  "가격비교",
                                                "seller":  "네이버쇼핑 검색",
                                                "status":  "조사 중",
                                                "displayPrice":  null,
                                                "finalPrice":  null,
                                                "referencePrice":  null,
                                                "condition":  "정확한 MTM과 용량 일치 여부 자동 확인 대기",
                                                "sourceType":  "네이버쇼핑 검색",
                                                "checkedAt":  "미확인",
                                                "confidence":  "C",
                                                "confidenceText":  "초기 검증 대기",
                                                "url":  "https://search.shopping.naver.com/search/all?query=SF16-71T-7475"
                                            }
                                        ]
                     }
                 ]
};
