window.MARKET_DATA = {
  "meta": {
    "snapshotAt": "2026-10-01T14:17:15+09:00",
    "sourceFile": "product-catalog.json",
    "comparisonBasis": "Exact model and item price comparison",
    "exclusions": "Personal rewards and unverified benefits are excluded",
    "monitoring": {
      "enabled": true,
      "quickWatch": "매일 08:00 · 14:00 KST",
      "fullResearch": "Basic and precision scan",
      "dashboardSync": "GitHub Pages automatic deployment",
      "lastAttemptAt": "2026-10-01T14:17:15+09:00",
      "lastAttemptStatus": "success",
      "lastAttemptText": "Godox 수집 결과: 검증 0, 품절 1, 일부 0 / 전체 1",
      "collectionRoute": "Windows PC · 일반 Chrome 확장프로그램",
      "competitionLastAttemptAt": "2026-10-01T14:17:15+09:00",
      "alertEvaluation": "",
      "competitionValidationStatus": "awaiting-1.9.27-scan"
    },
    "brand": "Godox",
    "publishedAt": "2026-10-01T15:21:06+09:00"
  },
  "products": [
    {
      "storage": "",
      "display": "C100",
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "shipping": 0,
          "finalPrice": 41160,
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "품절",
          "displayPrice": 42000,
          "instantDiscount": 10,
          "couponDiscount": null,
          "cardDiscount": null,
          "condition": "정확한 Item ID 확인. 품절 상품의 주문서 쿠폰은 미확인.",
          "sourceType": "관리화면 등록 URL",
          "checkedAt": "2026-10-01 14:01",
          "confidence": "A",
          "confidenceText": "동일 Item ID의 일반 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9738958594?itemId=29147698397&vendorItemId=96070924334",
          "checkoutInferredZeroFields": [],
          "lastVerifiedFinalPrice": 41160,
          "lastVerifiedPriceCheckedAt": "2026-09-24 08:00",
          "availabilityCheckedAt": "2026-10-01 14:01",
          "srp": 42000,
          "observedListPrice": 41990,
          "productPagePrice": 41990,
          "preCardPrice": null,
          "priceBasisType": "top-visible",
          "cardBenefitStatus": "none",
          "cardEvidenceSource": "",
          "cardRate": null,
          "cardMaxDiscount": null,
          "cardProviders": [],
          "cardTerms": [],
          "cardBenefitText": "",
          "checkoutDiscountStatus": "soldout",
          "checkoutDiscountReason": "buy-now-button-not-found",
          "checkoutCouponDiscount": null,
          "checkoutCouponSource": null,
          "wowInstantDiscount": null,
          "wowCouponDiscount": null,
          "checkoutDiscountCheckedAt": "",
          "checkoutUnparsedFields": [],
          "checkoutDiscountFieldStatus": null,
          "checkoutDiscountEvidence": [],
          "alertEligible": false,
          "priceChange": null,
          "priceTrend": "unavailable",
          "priceComparisonAt": "2026-09-24 08:00",
          "priceCheckedAt": "2026-10-01 14:01"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "재검증 대기",
          "displayPrice": 42000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 42000,
          "shipping": 0,
          "alertEligible": false,
          "competitionPolicyVerified": false,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와",
          "productTitle": "",
          "priceLabel": "42,000 원 무료배송",
          "checkedAt": "2026-10-01 14:01",
          "priceCheckedAt": "2026-10-01 14:01",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507",
          "validationReason": "legacy-seller-row-and-shipping-evidence-missing"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "오늘의집",
          "status": "재검증 대기",
          "displayPrice": 42000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 42000,
          "shipping": 0,
          "alertEligible": false,
          "competitionPolicyVerified": false,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와",
          "productTitle": "",
          "priceLabel": "42,000 원 3,000원 최대 15개월",
          "checkedAt": "2026-10-01 14:01",
          "priceCheckedAt": "2026-10-01 14:01",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507",
          "validationReason": "legacy-seller-row-and-shipping-evidence-missing"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "재검증 대기",
          "displayPrice": 42840,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 42840,
          "shipping": 0,
          "alertEligible": false,
          "competitionPolicyVerified": false,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와",
          "productTitle": "",
          "priceLabel": "42,840 원 빠른배송 무료배송",
          "checkedAt": "2026-10-01 14:01",
          "priceCheckedAt": "2026-10-01 14:01",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507",
          "validationReason": "legacy-seller-row-and-shipping-evidence-missing"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "재검증 대기",
          "displayPrice": 42850,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 42850,
          "shipping": 0,
          "alertEligible": false,
          "competitionPolicyVerified": false,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와",
          "productTitle": "",
          "priceLabel": "42,850 원 빠른배송 무료배송",
          "checkedAt": "2026-10-01 14:01",
          "priceCheckedAt": "2026-10-01 14:01",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507",
          "validationReason": "legacy-seller-row-and-shipping-evidence-missing"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "재검증 대기",
          "displayPrice": 43110,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 43110,
          "shipping": 0,
          "alertEligible": false,
          "competitionPolicyVerified": false,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "에누리",
          "productTitle": "[오늘출발] Godox 고독스 C100 투명 뷰파인더 포켓 카메라 C타입 세기 정품 AS가능 / 당일발송",
          "priceLabel": "[오늘출발] Godox 고독스 C100 투명 뷰파인더 포켓 카메라 C타입 세기 정품 AS가능 / 당일발송 평일 14:00까지 주문 시 120점 적립 에누리 앱에서 구매 시 신고 43,110원 G마켓삼성카드 41,610원 3,000원 - 구매하기 (새 창 열림)",
          "checkedAt": "2026-10-01 14:01",
          "priceCheckedAt": "2026-10-01 14:01",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://price.enuri.com/catalog/148559067",
          "validationReason": "legacy-seller-row-and-shipping-evidence-missing"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "이마트몰",
          "status": "재검증 대기",
          "displayPrice": 43280,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 43280,
          "shipping": 0,
          "alertEligible": false,
          "competitionPolicyVerified": false,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와",
          "productTitle": "",
          "priceLabel": "43,280 원 빠른배송 무료배송",
          "checkedAt": "2026-10-01 14:01",
          "priceCheckedAt": "2026-10-01 14:01",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507",
          "validationReason": "legacy-seller-row-and-shipping-evidence-missing"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "SSG.COM",
          "status": "재검증 대기",
          "displayPrice": 43280,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 43280,
          "shipping": 0,
          "alertEligible": false,
          "competitionPolicyVerified": false,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와",
          "productTitle": "",
          "priceLabel": "43,280 원 빠른배송 무료배송",
          "checkedAt": "2026-10-01 14:01",
          "priceCheckedAt": "2026-10-01 14:01",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507",
          "validationReason": "legacy-seller-row-and-shipping-evidence-missing"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "신세계몰",
          "status": "재검증 대기",
          "displayPrice": 43280,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 43280,
          "shipping": 0,
          "alertEligible": false,
          "competitionPolicyVerified": false,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와",
          "productTitle": "",
          "priceLabel": "43,280 원 빠른배송 무료배송",
          "checkedAt": "2026-10-01 14:01",
          "priceCheckedAt": "2026-10-01 14:01",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507",
          "validationReason": "legacy-seller-row-and-shipping-evidence-missing"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "재검증 대기",
          "displayPrice": 44030,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 44030,
          "shipping": 0,
          "alertEligible": false,
          "competitionPolicyVerified": false,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "에누리",
          "productTitle": "[오늘출발] 고독스 Godox C100",
          "priceLabel": "[오늘출발] 고독스 Godox C100 평일 15:00까지 주문 시 130점 적립 에누리 앱에서 구매 시 신고 44,030원 3,000원 - 구매하기 (새 창 열림)",
          "checkedAt": "2026-10-01 14:01",
          "priceCheckedAt": "2026-10-01 14:01",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://price.enuri.com/catalog/148559067",
          "validationReason": "legacy-seller-row-and-shipping-evidence-missing"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "재검증 대기",
          "displayPrice": 44100,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 44100,
          "shipping": 0,
          "alertEligible": false,
          "competitionPolicyVerified": false,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "에누리",
          "productTitle": "GODOX 고독스 C100 투명 뷰파인더 카메라 브이로그 OTG전송 케이블 포함 빈티지 감성과 기능의 결합",
          "priceLabel": "GODOX 고독스 C100 투명 뷰파인더 카메라 브이로그 OTG전송 케이블 포함 빈티지 감성과 기능의 결합 130점 적립 에누리 앱에서 구매 시 신고 44,100원 G마켓삼성카드 42,600원 무료배송 - 구매하기 (새 창 열림)",
          "checkedAt": "2026-10-01 14:01",
          "priceCheckedAt": "2026-10-01 14:01",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://price.enuri.com/catalog/148559067",
          "validationReason": "legacy-seller-row-and-shipping-evidence-missing"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "재검증 대기",
          "displayPrice": 44900,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 44900,
          "shipping": 0,
          "alertEligible": false,
          "competitionPolicyVerified": false,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "에누리",
          "productTitle": "[오늘출발] 고독스 Godox 고독스 C100 투명 뷰파인더 포켓 카메라 C타입 세기 정품 AS가능 / 당일발송",
          "priceLabel": "[오늘출발] 고독스 Godox 고독스 C100 투명 뷰파인더 포켓 카메라 C타입 세기 정품 AS가능 / 당일발송 평일 14:00까지 주문 시 130점 적립 에누리 앱에서 구매 시 신고 44,900원 3,000원 - 구매하기 (새 창 열림)",
          "checkedAt": "2026-10-01 14:01",
          "priceCheckedAt": "2026-10-01 14:01",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://price.enuri.com/catalog/148559067",
          "validationReason": "legacy-seller-row-and-shipping-evidence-missing"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "롯데ON",
          "status": "재검증 대기",
          "displayPrice": 45000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 45000,
          "shipping": 0,
          "alertEligible": false,
          "competitionPolicyVerified": false,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와",
          "productTitle": "",
          "priceLabel": "45,000 원 빠른배송 3,500원",
          "checkedAt": "2026-10-01 14:01",
          "priceCheckedAt": "2026-10-01 14:01",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507",
          "validationReason": "legacy-seller-row-and-shipping-evidence-missing"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "재검증 대기",
          "displayPrice": 45000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 45000,
          "shipping": 0,
          "alertEligible": false,
          "competitionPolicyVerified": false,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "에누리",
          "productTitle": "GODOX 고독스 C100 투명 뷰파인더 카메라 브이로그 OTG전송 케이블 포함 빈티지 감성과 기능의 결합",
          "priceLabel": "GODOX 고독스 C100 투명 뷰파인더 카메라 브이로그 OTG전송 케이블 포함 빈티지 감성과 기능의 결합 130점 적립 에누리 앱에서 구매 시 신고 45,000원 무료배송 - 구매하기 (새 창 열림)",
          "checkedAt": "2026-10-01 14:01",
          "priceCheckedAt": "2026-10-01 14:01",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://price.enuri.com/catalog/148559067",
          "validationReason": "legacy-seller-row-and-shipping-evidence-missing"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "Price comparison",
          "seller": "Danawa",
          "status": "Waiting for scan",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "Exact MTM comparison",
          "sourceType": "Danawa product page",
          "checkedAt": "",
          "confidence": "C",
          "confidenceText": "Waiting for first scan",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507"
        }
      ],
      "mtm": "C100",
      "productId": "9738958594",
      "itemId": "29147698397",
      "vendorItemId": "96070924334",
      "category": "Camera",
      "srp": 42000
    }
  ]
};
