window.MARKET_DATA = {
  "meta": {
    "brand": "Godox",
    "snapshotAt": "2026-09-24T08:19:16+09:00",
    "sourceFile": "product-catalog.json",
    "comparisonBasis": "Exact model and item price comparison",
    "exclusions": "Personal rewards and unverified benefits are excluded",
    "monitoring": {
      "enabled": true,
      "quickWatch": "매일 08:00 · 14:00 KST",
      "fullResearch": "Basic and precision scan",
      "dashboardSync": "GitHub Pages automatic deployment",
      "lastAttemptAt": "2026-09-24T08:19:16+09:00",
      "lastAttemptStatus": "success",
      "lastAttemptText": "Godox 수집 결과: 검증 1, 품절 0, 일부 0 / 전체 1",
      "collectionRoute": "Windows PC · 일반 Chrome 확장프로그램",
      "competitionLastAttemptAt": "2026-09-24T08:19:16+09:00"
    }
  },
  "products": [
    {
      "mtm": "C100",
      "storage": "",
      "display": "C100",
      "productId": "9738958594",
      "itemId": "29147698397",
      "vendorItemId": "96070924334",
      "category": "Camera",
      "srp": 42000,
      "validation": "identifiers-verified",
      "offers": [
        {
          "role": "mine",
          "shipping": 0,
          "finalPrice": 41160,
          "channel": "쿠팡",
          "seller": "내 쿠팡 상품",
          "status": "현재가 직접 확인",
          "displayPrice": 42000,
          "instantDiscount": 840,
          "couponDiscount": 0,
          "cardDiscount": 0,
          "condition": "정확한 Item ID와 상품페이지·주문서 할인을 직접 확인.",
          "sourceType": "관리화면 등록 URL",
          "checkedAt": "2026-09-24 08:00",
          "availabilityCheckedAt": "2026-09-24 08:00",
          "priceCheckedAt": "2026-09-24 08:00",
          "confidence": "A",
          "confidenceText": "동일 Item ID의 일반 Chrome 화면에서 가격 확인",
          "url": "https://www.coupang.com/vp/products/9738958594?itemId=29147698397&vendorItemId=96070924334",
          "srp": 42000,
          "observedListPrice": 41160,
          "productPagePrice": 41160,
          "preCardPrice": 41160,
          "priceBasisType": "top-visible",
          "cardBenefitStatus": "none",
          "cardRate": null,
          "cardMaxDiscount": null,
          "cardProviders": [],
          "cardBenefitText": "",
          "checkoutDiscountStatus": "captured",
          "checkoutDiscountReason": "checkout-confirmed-absent-discount-fields-zero",
          "checkoutCouponDiscount": 0,
          "checkoutCouponSource": "checkout",
          "wowInstantDiscount": 0,
          "wowCouponDiscount": 0,
          "checkoutDiscountCheckedAt": "2026-09-23T23:01:11.762Z",
          "checkoutUnparsedFields": [],
          "checkoutDiscountFieldStatus": null,
          "checkoutDiscountEvidence": [],
          "alertEligible": true,
          "priceChange": null,
          "priceTrend": "unavailable",
          "priceComparisonAt": "",
          "lastVerifiedFinalPrice": 41160,
          "lastVerifiedPriceCheckedAt": "2026-09-24 08:00"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "옥션",
          "status": "판매중",
          "displayPrice": 41950,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 41950,
          "shipping": 0,
          "alertEligible": true,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-24 08:00",
          "priceCheckedAt": "2026-09-24 08:00",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "G마켓",
          "status": "판매중",
          "displayPrice": 41950,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 41950,
          "shipping": 0,
          "alertEligible": true,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-24 08:00",
          "priceCheckedAt": "2026-09-24 08:00",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "쿠팡",
          "status": "판매중",
          "displayPrice": 42000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 42000,
          "shipping": 0,
          "alertEligible": true,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-24 08:00",
          "priceCheckedAt": "2026-09-24 08:00",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "오늘의집",
          "status": "판매중",
          "displayPrice": 42000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 42000,
          "shipping": 0,
          "alertEligible": true,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-24 08:00",
          "priceCheckedAt": "2026-09-24 08:00",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "11번가",
          "status": "판매중",
          "displayPrice": 42000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 42000,
          "shipping": 0,
          "alertEligible": true,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-24 08:00",
          "priceCheckedAt": "2026-09-24 08:00",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "이마트몰",
          "status": "판매중",
          "displayPrice": 43010,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 43010,
          "shipping": 0,
          "alertEligible": true,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-24 08:00",
          "priceCheckedAt": "2026-09-24 08:00",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507"
        },
        {
          "role": "competitor",
          "channel": "전문몰",
          "seller": "신세계몰",
          "status": "판매중",
          "displayPrice": 43010,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 43010,
          "shipping": 0,
          "alertEligible": true,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-24 08:00",
          "priceCheckedAt": "2026-09-24 08:00",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "SSG.COM",
          "status": "판매중",
          "displayPrice": 43010,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 43010,
          "shipping": 0,
          "alertEligible": true,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-24 08:00",
          "priceCheckedAt": "2026-09-24 08:00",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507"
        },
        {
          "role": "competitor",
          "channel": "오픈마켓",
          "seller": "롯데ON",
          "status": "판매중",
          "displayPrice": 45000,
          "instantDiscount": null,
          "couponDiscount": null,
          "cardDiscount": null,
          "finalPrice": 45000,
          "shipping": 0,
          "alertEligible": true,
          "condition": "다나와 배송비 포함 공개 판매가. 추가 쿠폰·카드할인은 미확인.",
          "sourceType": "다나와 가격비교 판매처 목록",
          "checkedAt": "2026-09-24 08:00",
          "priceCheckedAt": "2026-09-24 08:00",
          "confidence": "B",
          "confidenceText": "정확한 MTM의 쇼핑몰별 판매가를 일반 Chrome에서 확인",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507"
        }
      ],
      "references": [
        {
          "role": "competitor",
          "channel": "Price comparison",
          "seller": "Danawa",
          "status": "Waiting for scan",
          "displayPrice": null,
          "finalPrice": null,
          "referencePrice": null,
          "condition": "Exact MTM comparison",
          "sourceType": "Danawa product page",
          "checkedAt": "",
          "confidence": "C",
          "confidenceText": "Waiting for first scan",
          "url": "https://prod.danawa.com/info/?pcode=124247591&keyword=%EA%B3%A0%EB%8F%85%EC%8A%A4+c100&cate=12237507"
        }
      ]
    }
  ]
};
